version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: web.docker
        volumes:
            - ..:/var/www/html
        ports:
            - "8080:8080"
        links:
            - app
    app:
        build:
            context: ./
            dockerfile: app.docker
        volumes:
            - ..:/var/www/html
    gulp:
        build:
            context: ./
            dockerfile: gulp.docker
        volumes_from:
            - app
    composer:
        build:
            context: ./
            dockerfile: composer.docker
        volumes_from:
            - app
    npm:
        build:
            context: ./
            dockerfile: npm.docker
        volumes_from:
            - app
